
project_id = "cnongijjpbsgysdophin"

[functions.analyze-sentiment-perplexity]

[functions.check-reveals]

[functions.send-capsule-notification]

[functions.analyze-sentiment]

[functions.analyze-capsule-responses]
